sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez sales / we have one row per each product_id found
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        columns:
          - name: "date_date"
            description: "the date of purchase"
          - name: "orders_id"
            description: "foreign key to ship"
          - name: "pdt_id"
            description: "foreign key to product"
          - name: "quantity"
            description: "the amount paid by the customer to purchase the product"
          - name: "quantity"
            description: "the quantity of products purchased for this order"
        tests:
          - unique:
              column_name: "(orders_id || '-'|| pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: Greenweez products
        columns:
          - name: products_id
            description: table primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price of a product
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez ship
        columns:
          - name: orders_id
            description: table primary key
            tests:
              - unique
              - not_null
      - name: shipping_fee
        description: the price the customer pays for shipping
      - name: log_cost
        description: the cost of preparing the parcen in the werehouse
      - name: ship_cost
        description: the shipping cost paid by Greenweez to the carrier/transporter
      - name: raw_gz_adwords
        description: Raw data from Google AdWords
        columns:
          - name: date_date
            description: Date of the ad
          - name: paid_source
            description: The source of the advertisement
          - name: campaign_key
            description: The campaign key
          - name: campaign_name
            description: The name of the campaign
          - name: ads_cost
            description: Cost of the advertisement
          - name: impression
            description: Number of impressions
          - name: click
            description: Number of clicks
            tests:
              - not_null

      - name: raw_gz_bing
        description: Raw data from Bing Ads
        columns:
          - name: date_date
            description: Date of the ad
          - name: paid_source
            description: The source of the advertisement
          - name: campaign_key
            description: The campaign key
          - name: campaign_name
            description: The name of the campaign
          - name: ads_cost
            description: Cost of the advertisement
          - name: impression
            description: Number of impressions
          - name: click
            description: Number of clicks
            tests:
              - not_null

      - name: raw_gz_criteo
        description: Raw data from Criteo
        columns:
          - name: date_date
            description: Date of the ad
          - name: paid_source
            description: The source of the advertisement
          - name: campaign_key
            description: The campaign key
          - name: campaign_name
            description: The name of the campaign
          - name: ads_cost
            description: Cost of the advertisement
          - name: impression
            description: Number of impressions
          - name: click
            description: Number of clicks
            tests:
              - not_null

      - name: raw_gz_facebook
        description: Raw data from Facebook Ads
        columns:
          - name: date_date
            description: Date of the ad
          - name: paid_source
            description: The source of the advertisement
          - name: campaign_key
            description: The campaign key
          - name: campaign_name
            description: The name of the campaign
          - name: ads_cost
            description: Cost of the advertisement
          - name: impression
            description: Number of impressions
          - name: click
            description: Number of clicks
            tests:
              - not_null
 
models:
  - name: stg_raw_product
  - name: stg_raw_sales
  - name: stg_raw_ship
  - name: stg_raw__raw_gz_adwords
  - name: stg_raw__raw_gz_bing
  - name: stg_raw__raw_gz_criteo
  - name: stg_raw__raw_gz_facebook
  - name: int_sales_margin
    description: margin calculation per order line / product sale
    columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
    tests:
      - unique:
          column_name: "(orders_id || '-'|| products_id)"
      - not_null:
          column_name: orders_id
      - not_null:
          column_name: products_id
      - not_null:
          column_name: margin
      - not_null:
          column_name: Purchase_cost
      - not_null:
          column_name: date_date
      - not_null:
          column_name: revenue
      - not_null:
          column_name: quantity
    
  - name: int_campaign_day
    description: "Modelo que agrega los costos de publicidad, impresiones y clics."
    columns:
      - name: date_date
        description: "Fecha en la que se registraron los datos de la campaña."
        tests:
          - not_null
          - unique
      - name: ads_cost
        description: "Costo total de la publicidad en la fecha dada."
        tests:
          - not_null
      - name: ads_impressions
        description: "Número total de impresiones de los anuncios en la fecha dada."
        tests:
          - not_null
      - name: ads_clicks
        description: "Número total de clics en los anuncios en la fecha dada."
        tests:
          - not_null
